name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * 6,2'
  workflow_run: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
